# Generated by Django 3.1.7 on 2021-03-21 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wishlist', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userswishlist',
            name='wishlist',
            field=models.TextField(),
        ),
    ]
