# Generated by Django 3.1.7 on 2021-03-21 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0001_initial'),
        ('wishlist', '0002_auto_20210321_1431'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userswishlist',
            name='wishlist',
        ),
        migrations.AddField(
            model_name='userswishlist',
            name='items',
            field=models.ManyToManyField(to='stock.Item'),
        ),
    ]
