# Generated by Django 3.1.7 on 2021-03-21 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0001_initial'),
        ('wishlist', '0003_auto_20210321_1543'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userswishlist',
            name='items',
            field=models.ManyToManyField(default='', to='stock.Item'),
        ),
    ]
