# Generated by Django 3.1.7 on 2021-03-06 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='town_or_city',
            field=models.CharField(default='dublin', max_length=50),
            preserve_default=False,
        ),
    ]
