# Generated by Django 3.1.7 on 2021-03-10 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0002_order_town_or_city'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='eircode',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='street_address_2',
            field=models.CharField(blank=True, max_length=80, null=True),
        ),
    ]
