# Generated by Django 3.1.7 on 2021-03-14 15:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0008_order_user_profile'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='subtotal',
            new_name='grand_total',
        ),
    ]
