# Generated by Django 3.1.7 on 2021-03-14 17:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='NewsletterSubscribers',
            new_name='Newsletter',
        ),
    ]
