# Generated by Django 3.1.7 on 2021-03-14 17:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0003_auto_20210314_1747'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='NewsletterSubscribers',
            new_name='NewsletterSubscriber',
        ),
    ]
