# Generated by Django 3.1.7 on 2021-03-15 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0004_auto_20210314_1750'),
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=100)),
                ('user_email', models.EmailField(max_length=254)),
                ('message', models.TextField()),
            ],
        ),
    ]
